const fs = require('fs');
const path = require('path');
const {
  withDangerousMod,
  withAndroidManifest,
  withMainApplication,
  AndroidConfig,
} = require('@expo/config-plugins');

const { getMainApplicationOrThrow } = AndroidConfig.Manifest;

const PACKAGE_PATH = 'com/catalyst/essentials';
const SOURCE_DIR = 'widget-native';

/**
 * Copies the hand-written native widget source (Kotlin + res/) from
 * ./widget-native into the generated android/ project. android/ is
 * gitignored and regenerated by `expo prebuild`, so this plugin is the
 * only thing keeping the water widget alive across a clean prebuild.
 */
function copyRecursive(srcDir, destDir) {
  if (!fs.existsSync(srcDir)) return;
  fs.mkdirSync(destDir, { recursive: true });
  for (const entry of fs.readdirSync(srcDir, { withFileTypes: true })) {
    const srcPath = path.join(srcDir, entry.name);
    const destPath = path.join(destDir, entry.name);
    if (entry.isDirectory()) {
      copyRecursive(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

const withWidgetFiles = (config) =>
  withDangerousMod(config, [
    'android',
    async (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const androidRoot = config.modRequest.platformProjectRoot;
      const widgetSrcRoot = path.join(projectRoot, SOURCE_DIR);

      // Kotlin sources → app/src/main/java/com/catalyst/essentials/
      const javaDest = path.join(androidRoot, 'app/src/main/java', PACKAGE_PATH);
      fs.mkdirSync(javaDest, { recursive: true });
      for (const file of fs.readdirSync(widgetSrcRoot)) {
        if (file.endsWith('.kt')) {
          fs.copyFileSync(path.join(widgetSrcRoot, file), path.join(javaDest, file));
        }
      }

      // Resources → app/src/main/res/**
      const resSrc = path.join(widgetSrcRoot, 'res');
      const resDest = path.join(androidRoot, 'app/src/main/res');
      copyRecursive(resSrc, resDest);

      return config;
    },
  ]);

const withWidgetManifest = (config) =>
  withAndroidManifest(config, (config) => {
    const app = getMainApplicationOrThrow(config.modResults);

    if (!Array.isArray(app.receiver)) {
      app.receiver = [];
    }

    const alreadyRegistered = app.receiver.some(
      (r) => r.$?.['android:name'] === '.WaterWidgetProvider'
    );

    if (!alreadyRegistered) {
      app.receiver.push({
        $: {
          'android:name': '.WaterWidgetProvider',
          // Must be exported — the launcher (a different app/process) is
          // what actually dispatches APPWIDGET_UPDATE to this receiver.
          'android:exported': 'true',
          'android:label': 'Hydration',
        },
        'intent-filter': [
          {
            action: [
              { $: { 'android:name': 'android.appwidget.action.APPWIDGET_UPDATE' } },
            ],
          },
        ],
        'meta-data': [
          {
            $: {
              'android:name': 'android.appwidget.provider',
              'android:resource': '@xml/widget_water_info',
            },
          },
        ],
      });
    }

    const quickLogAlreadyRegistered = app.receiver.some(
      (r) => r.$?.['android:name'] === '.WidgetQuickLogReceiver'
    );

    if (!quickLogAlreadyRegistered) {
      app.receiver.push({
        $: {
          'android:name': '.WidgetQuickLogReceiver',
          // Exported for the same reason as WaterWidgetProvider above — the
          // PendingIntent is fired via the launcher/AppWidgetHost process.
          'android:exported': 'true',
        },
      });
    }

    if (!Array.isArray(app.service)) {
      app.service = [];
    }

    const taskServiceAlreadyRegistered = app.service.some(
      (s) => s.$?.['android:name'] === '.WidgetQuickLogTaskService'
    );

    if (!taskServiceAlreadyRegistered) {
      app.service.push({
        $: {
          'android:name': '.WidgetQuickLogTaskService',
          'android:exported': 'false',
        },
      });
    }

    return config;
  });

const withWidgetNativeModule = (config) =>
  withMainApplication(config, (config) => {
    const contents = config.modResults.contents;
    if (contents.includes('WidgetPackage()')) {
      return config;
    }

    config.modResults.contents = contents.replace(
      /(PackageList\(this\)\.packages\.apply\s*\{)/,
      `$1\n          add(WidgetPackage())`
    );

    return config;
  });

module.exports = function withWaterWidget(config) {
  config = withWidgetFiles(config);
  config = withWidgetManifest(config);
  config = withWidgetNativeModule(config);
  return config;
};
